name: Create a release Releases

on: 
  push:
    tags:
    - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Maven Central Repository
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Create Artifact
      run: mvn --batch-mode clean package
    - run: mkdir staging && cp target/*.jar staging
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging      
    - name: Create Release with Artifact
      uses: ncipollo/release-action@v1
      with:
        body: "Release from Tag"
        artifacts: "get*.jar"
        token: ${{ secrets.GITHUB_TOKEN }}